name: ssy226
channels:
- defaults
dependencies:
- python=3.7
- pip
- numpy
- jupyter
- matplotlib
- scikit-learn
- scipy
- pandas
- seaborn
- unidecode
- pip:
  - pillow
  - pyvisgraph==0.2.1
  - opengen==0.6.4
  - casadi
  - extremitypathfinder>=2.1.0
  - pyclipper
